### ISSUE TITLE
Push kit  - NullPointerException

### ISSUE THREAD

**Issue by jjsebastianfuertes** [HMS-Core/hms-flutter-plugin#115] opened 2021-09-26 11:57 UTC
**Description**
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference

**Current behavior**
This issue happens 100% in background state of the device

**Logs**

```
com.huawei.hms.flutter.push.hms.PluginContext.getContext (PluginContext.java:36)
com.huawei.hms.flutter.push.hms.FlutterHmsMessageService.onNewToken (FlutterHmsMessageService.java:50)
com.huawei.hms.push.HmsMessageService.a (HmsMessageService.java:55)
com.huawei.hms.push.HmsMessageService.a (HmsMessageService.java:27)
com.huawei.hms.push.HmsMessageService.handleIntentMessage (HmsMessageService.java:7)
com.huawei.hms.push.HmsMessageService$a.handleMessage (HmsMessageService.java:7)
android.os.Handler.dispatchMessage (Handler.java:108)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:7529)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
```

**Environment**
 - Platform: Flutter 2.5.0
 - Kit: PUSH
 - Kit Version 5.1.1+301
 - OS Version Android 11, 10, 9

**Comment by atavci** [comment] 2021-09-27 06:14
Duplicate of #92. This issue is caused by Auto Initialization on the background where there is no application context. We already applied a patch for it,  you can keep an eye on our [pub.dev](https://pub.dev/packages/huawei_push) repository for the next release that is going to be at the end of this month. 

Best.

**Closed** 2021-10-01 08:37 UTC
