### ISSUE TITLE
Some sessions show error on HMSLogger with push_kit

### ISSUE THREAD

**Issue by fleoparra** [HMS-Core/hms-flutter-plugin#73] opened 2021-03-17 21:34 UTC
I am using huawei_push: ^5.0.2+303

I use crashlytics for log errors on my app.

In this moment, major amount of errors show me the following log:

 HMSLogger.java line 292 

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
com.huawei.hms.flutter.push.logger.HMSLogger.setupEventMap (HMSLogger.java:292)
com.huawei.hms.flutter.push.logger.HMSLogger.<init> (HMSLogger.java:78)
com.huawei.hms.flutter.push.logger.HMSLogger.getInstance (HMSLogger.java:95)
com.huawei.hms.flutter.push.hms.FlutterHmsMessageService.onNewToken (FlutterHmsMessageService.java:48)
com.huawei.hms.push.HmsMessageService.a (HmsMessageService.java:246)
com.huawei.hms.push.HmsMessageService.a (HmsMessageService.java:180)
com.huawei.hms.push.HmsMessageService.a (HmsMessageService.java:39)
com.huawei.hms.push.HmsMessageService$a.handleMessage (HmsMessageService.java:162)

I am not sure how can I replicate this error, but the amount is like 2% of the sessions.

**Comment by atavci** [comment] 2021-03-18 07:47
Hello,

We believe this exception is raised when the application tries to obtain a token while it is on the background. 
Can you share the following information in order for us to reproduce this issue ?
- `flutter doctor` command output
- The Android version that you had specified in your project.
- The EMUI version of your device.
- Is the Auto-Initialization feature of the Push Kit enabled ?
- If possible, code sample that you use to obtain the push token.

Thank you for informing us about this issue, we will provide a fix as soon as we find the root cause.

**Comment by alfred-risb** [comment] 2021-03-19 15:44
I have the same issue, my code is just a simple initialization

`
String token = '';

void _onTokenEvent(String event) {
    token = event;
  }

  void _onTokenError(Object error) {
    print("TokenEvent: $error");
  }

  void _onMessageReceived(RemoteMessage rm) {
    String data = rm.data;
    print(data);
  }

  void _onMessageReceiveError(Object error) {
    print("DataMessageError: $error");
  }

Future<void> initPlatformState() async {
    await Push.setAutoInitEnabled(true);
    Push.getTokenStream.listen(_onTokenEvent, onError: _onTokenError);
    await Push.getToken("");
    Push.onMessageReceivedStream
        .listen(_onMessageReceived, onError: _onMessageReceiveError);
  }
`

![Screenshot 2021-03-19 at 11 40 03 PM](https://user-images.githubusercontent.com/39892484/111805980-79bd6400-890c-11eb-886a-0b6cda3d8594.png)
![Screenshot 2021-03-19 at 11 40 12 PM](https://user-images.githubusercontent.com/39892484/111805998-7e821800-890c-11eb-98d7-48981cd0e1e1.png)

**Comment by atavci** [comment] 2021-03-22 13:15
Hello again,

We have successfully reproduced this error and found a solution. On our upcoming release for Push Kit Flutter Plugin 5.0.2+304 this issue won't be raised again.

Thank you for the error report. 👍 I wish you a great day.

**Comment by atavci** [comment] 2021-04-08 10:31
**Update:** We have provided a fix for this error in our latest release 5.0.2+304. You may download the newest package from [pub.dev](https://pub.dev/packages/huawei_push).

**Closed** 2021-04-08 10:31 UTC
