### ISSUE TITLE
[huawei_iap] Huawei Sign-In Activity not opening automatically

### ISSUE THREAD

**Issue by deniza** [HMS-Core/hms-flutter-plugin#32] opened 2020-10-23 09:39 UTC
Calling **IapClient.isEnvReady()** throws PlatformException if the user did not login with his/her HUAWEI ID on device before.

This should be handled by opening required login/sign-in Activity automatically. As far as i understand, with my little to none native code experience, there is some code to handle this in **IsEnvReadyFailureListener.java** but it's not working.

**Comment by deniza** [comment] 2020-10-23 11:47
I am running some tests on some actual remote devices using HMS Cloud Debugging. It seems that IapClient.isEnvReady() always throws Platform exception with returnCode: -5. It does not matter if you login using HUAWEI id or not.

I cloned official android sample from https://github.com/HMS-Core/hms-iap-clientdemo-android-studio
Then changed its configuration to match my apps actual config setup and everything is working just fine.

So, either there is a problem with flutter plugin or I am doing something wrong on flutter/HMS configuration.

**Comment by deniza** [comment] 2020-10-23 15:49
I solved the issue. My app level build.gradle file has **minifyEnabled=true** configuration parameter which causes the problem.

```
...
buildTypes {
   release {
      minifyEnabled true
      signingConfig signingConfigs.config
   }
}
...
```

After removing it everything started to work as expected. 

In case if you are getting **PlatformException(-5, Core error, null, null)** remember to check minifyEnabled flag in app level build.gradle.

I guess somebody need to use this flag somehow. We need to update the documentation or better find out why this flag creates so much trouble and fix it.

**Comment by SerdarCanDev** [comment] 2020-10-23 16:43
Hi @deniza , glad to hear that!

Let me explain the issue, this issue is actually caused by HMS Core itself rather than IAP Flutter Plugin. 

`minifyEnabled true` flag enables code shrinking, obfuscation, and optimization for your project's release build type. While obfuscating the project, HMS Core is also obfuscated and it should be prevented in order to work without issues. 

Before building the APK, configure the obfuscation configuration file to prevent the HMS Core SDK from being obfuscated, and then you may use `minifyEnabled true` flag. For details please refer to [Configuring Obfuscation Scripts](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/config-obfuscation-scripts-0000001050260710-V5).

After adding **proguard-rules.pro** file, change your app level **buil.gradle** file described below. 

``` gradle
...
buildTypes {
   release {
      // enables code shrinking, obfuscation, and optimization.
      minifyEnabled true 

      // enables resource shrinking.
      shrinkResources true 

      // the file you added
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
   }
}
...
```

I'm closing the issue since it is resolved. You may re-open the issue if the problem persists or open another issue if you encounter any other.

**Closed by SerdarCanDev** 2020-10-23 16:43 UTC
