### ISSUE TITLE
Add explicit `exported` value for PushMsgReceiver

### ISSUE THREAD

**Issue by medyas** [HMS-Core/hms-flutter-plugin#147] opened 2021-12-16 16:43 UTC
**Description**
Android 12 required adding `android:exported` to services/activities.

**Expected behavior**
App to be installed

**Current behavior**
app crashes on install to device

**Logs**
`Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl795607080.tmp/base.apk (at Binary XML file line #344): com.huawei.hms.support.api.push.PushMsgReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]`

**Environment**
 - Platform: Flutter
 - Kit: huawei_push
 - Kit Version : ^5.3.0+304
 - OS Version  Android 12
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.17763.2183], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)

**Comment by ozkulbeng** [comment] 2021-12-21 08:28
Hello @medyas 
This issue is duplicate of #144. Please check it.

**Comment by medyas** [comment] 2021-12-21 09:58
@ozkulbeng thanks, i did but its closed and reported since a month and yet no solution is released.
Like its an easy fix, could you provide information about when we should expect this to be resolved ?

**Comment by jjsebastianfuertes** [comment] 2022-03-02 19:28
@ozkulbeng  was this issue solved in version 6.1.0+300?

**Comment by xiaocode337317439** [comment] 2022-03-14 11:04
> @ozkulbeng 这个问题在 6.1.0+300 版本中解决了吗？

implementation 'com.huawei.hms:push:6.3.0.300' 版本都还有问题，感觉这个问题 从去年到今年 这么久了，这是咋了。。。

**Comment by Xuejiao-Shi** [comment] 2022-03-15 01:43
@xiaocode337317439 您好，建议您直接接入华为推送，我们试了6.3.0.300和6.3.0.302，都没有这个问题：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/android-app-version-0000001074227861#section136111021172810

**Comment by huseyinerenguler** [comment] 2022-04-05 11:07
Hi @medyas 

Latest version of [huawei_push](https://pub.dev/packages/huawei_push) was released on April 1st. With this version, we fixed some issues for adapting to Android 12. 

According to our recent tests, the issue appears to be resolved. Please test again with the [current version](https://pub.dev/packages/huawei_push/versions). 
If the issue persists, contact us here.

**Closed** 2022-04-08 15:02 UTC
