### ISSUE TITLE
IAP build error

### ISSUE THREAD

**Issue by KirisakiAria** [HMS-Core/hms-flutter-plugin#54] opened 2020-12-19 15:24 UTC
According to [this](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrating-sdk-0000001050761665-V1) , I configured these files.

And when I start debugging: 

> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > Android resource linking failed
>      H:\Project\name_generator\build\app\intermediates\merged_manifests\debug\AndroidManifest.xml:10: AAPT: error: not well-formed (invalid token).
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 35s
> The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
> Building plugin flutter_plugin_android_lifecycle...
> C:\Users\xiaol\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-1.0.11\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8: 错误: 程序包androidx.lifecycle不存在
> import androidx.lifecycle.Lifecycle;
>                          ^
> C:\Users\xiaol\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-1.0.11\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22: 错误: 找不到符号
>   public static Lifecycle getActivityLifecycle(
>                 ^
>   符号:   类 Lifecycle
>   位置: 类 FlutterLifecycleAdapter
> 2 个错误
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
> Exited (sigterm)

**IAP version: 5.0.2+300
Flutter version: Channel master, 1.26.0-2.0.pre.86, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN
Android toolchain: develop for Android devices (Android SDK version 30.0.3)**

If I remove all configuration items related to Huawei IAP, app can run debugging normally.

Please help me thanks!!!

**Comment by SerdarCanDev** [comment] 2020-12-20 18:19
Hi @KirisakiAria , thank you for reporting the issue. 

Regarding the provided logs, the issue is caused by FlutterLifecycleAdapter, and unfortunately, Huawei IAP Flutter Plugin doesn't use this plugin as a third-party plugin. To better analyze the issue, can you please provide your `AndroidManifest.xml` file and other plugins/packages that you used on your project?

**Comment by KirisakiAria** [comment] 2020-12-23 07:47
@SerdarCanDev Hello

This is my AndroidManifest.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.bigteacher.bianzizai">
    
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="@string/彼岸自在"
        android:icon="@mipmap/icon"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`

The dependencies which I use :

`environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  package_info: ^0.4.3+2
  provider: ^4.3.2+3
  transparent_image: ^1.0.0
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+17
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  flutter_screenutil: ^4.0.0
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  share: ^0.6.5+4
  flutter_staggered_grid_view: ^0.3.2
  like_button: ^1.0.4
  huawei_iap: ^5.0.2+300

dev_dependencies:
  flutter_test:
    sdk: flutter`

**Comment by SerdarCanDev** [comment] 2020-12-27 14:34
Hi @KirisakiAria , sorry for the late response, we were trying to analyze the behavior of your packages with our Huawei IAP Flutter Plugin. 

According to your logs, the issue is originated from `flutter_plugin_android_lifecycle` and, as mentioned earlier, `flutter_plugin_android_lifecycle` is not a package that used in Huawei IAP Flutter Plugin. Moreover, without implementing an actual working app, we created a simple project and add the mentioned packages to reproduce the error, but the default Flutter application successfully runs without any errors. Also, we tried adding your packages to our Huawei IAP Flutter Demo, which you can find in the `example` folder of our plugin, and the demo application runs successfully. Hence, we couldn't reproduce your issue. 

`flutter_plugin_android_lifecycle` is Flutter's own package that helps to manage lifecycle events from the Android part of the plugins. One of your packages named `image_picker`, is using this plugin as a third-party dependency. For identifying the source of the problem and to better analyze the issue, please try removing the code blocks and any configurations related to this package without removing the Huawei IAP configurations. If your problem persists, please provide a minimal reproducible project for us to further investigate the error.

**Comment by KirisakiAria** [comment] 2020-12-28 05:14
@SerdarCanDev Hi! Thank you very much for your reply!

I think I found the problem. I used Chinese character in "android:label", so it appeared corrupted characters when app was built. 

> build\app\intermediates\merged_manifests\debug\AndroidManifest.xml:10: AAPT: error: not well-formed (invalid token).
> android:label="�˰�����"

If I replace all Chinese character  with English character, the problem was fixed.

But what puzzles me is this problem occurs only when I use Huawei IAP. If I remove all configuration items related to Huawei IAP, app can run debugging normally.

It's very strange. 🤔

**Comment by SerdarCanDev** [comment] 2020-12-28 05:41
Hi @KirisakiAria , glad to hear that, and thank you for your collaboration.

It seems like a cache problem. When configuration needed packages, such as Huawei IAP, added to projects the build will significantly change so that the project will build itself again instead of using the cached files. Just to be sure, we will investigate your case with the provided information and solve the problem if there are any.  You may close this issue since it is resolved and you are always welcome if you encounter another problem. 😊

**Closed** 2020-12-28 06:13 UTC
