### ISSUE TITLE
cannot receive notification

### ISSUE THREAD

**Issue by Lawati97** [HMS-Core/hms-flutter-plugin#256] opened 2022-12-05 10:00 UTC
**Description**
I am trying to send notification from the backend or even from the notification center that is provided in Huawei ag connect but no notification is appearing or any function is being triggered
`Future<void> initPlatformState() async {

    // If you want auto init enabled, after getting user agreement call this method.

    await Push.setAutoInitEnabled(true);

    await Push.getTokenStream.listen(_onTokenEvent, onError: _onTokenError);

    await Push.getIntentStream.listen(_onNewIntent, onError: _onIntentError);

    await Push.onNotificationOpenedApp.listen(_onNotificationOpenedApp);

    dynamic initialNotification = await Push.getInitialNotification();

    _onNotificationOpenedApp(initialNotification);

    await Push.onLocalNotificationClick.listen(

      _onLocalNotificationClickEvent,

      onError: _onLocalNotificationClickErr,

    );

    String? intent = await Push.getInitialIntent();

    _onNewIntent(intent);

    await Push.onMessageReceivedStream.listen(

      _onMessageReceived,

      onError: _onMessageReceiveError,

    );

    Push.getRemoteMsgSendStatusStream.listen(

      _onRemoteMessageSendStatus,

      onError: _onRemoteMessageSendError,

    );`

**Logs**
[1:58 PM] Hussain Allawati (Thawani)
I/HMSSDK_HMSPackageManager(24066): Enter getHMSPackageNameForMultiService 
I/HMSSDK_HuaweiMobileServicesUtil(24066): hmsPackageName is com.huawei.hwid 
I/HMSSDK_HMSPackageManager(24066): enter checkHmsIsSpoof 
I/HMSSDK_HMSPackageManager(24066): quit checkHmsIsSpoof cached state: SUCCESS 
I/HMSSDK_HMSPackageManager(24066): Enter getHMSPackageNameForMultiService 
I/HMSSDK_HuaweiMobileServicesUtil(24066): connect versionCode:60800331 
I/HMSSDK_HMSPackageManager(24066): Enter getHMSPackageName 
I/HMSSDK_HMSPackageManager(24066): current versionCode:60800331, minimum version requirements: 30000100 
2I/HMSSDK_HMSPackageManager(24066): Enter getHMSPackageName 
I/HMSSDK_HMSPackageManager(24066): MinApkVersion is disabled.

I/HMSSDK_HMSPackageManager(24066): Enter getHMSPackageNameForMultiService 
I/HMSSDK_HMSBIInitializer(24066): Builder->biInitFlag :false

**Environment**
 - Platform: Flutter
 - Kit: Push
 - Kit Version 6.5.0+300

**Comment by Lawati97** [comment] 2022-12-05 10:00
Kindly note am calling the function in initPlatform in Splash Screen

**Comment by xuxiapu** [comment] 2022-12-06 02:42
Dear developer,

@Lawati97 Please confirm the following questions:
1. Can you get Push Token?
2. Are you sending an ordinary message or a data message? (If it is a normal message, you will see the notification message on your mobile phone after receiving it.)

**Comment by Lawati97** [comment] 2022-12-06 10:35
@xuxiapu 
1. I do get Push Token the first time i download the application 
2. I tried both and  wasn't able to see it

**Comment by xuxiapu** [comment] 2022-12-07 09:17
@Lawati97 Dear developer,
Hello, in order to help you solve all the problems better, please Submit a ticket online, and someone will be assigned to solve them in detail.
Link：https://developer.huawei.com/consumer/en/support/feedback/#/

**Comment by huseyinerenguler** [comment] 2023-01-19 12:52
Hi @Lawati97 

As the technical team, we tested Flutter Push plugin with [our demo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/flutter-sdk-download-0000001050186157-V1) application and we haven't reproduced the issue that you've been dealing. Our demo application is up to date and working properly. We recommend you to try our demo.

If you still have problem with sending notifications, as @xuxiapu mentioned before, you may submit a ticket online.

**Comment by mr-slonn** [comment] 2023-01-19 13:05
I stupidly spent two days, realizing that the application does not receive "Notifications", but receives "Information".
![2023-01-19_16-02-53](https://user-images.githubusercontent.com/11975624/213450113-2142b5f5-dcc1-4212-8814-f77a95c8e4cf.png)
Print screen in Russian, unfortunately did not find how to switch the language in the console.

**Comment by mr-slonn** [comment] 2023-01-19 14:22
Why do I receive a notification in the application if I send "Information", and if I send "Notification", then I do not receive it in the application, but I receive it in the phone's notification manager?

So I sent a notification and received it on my phone, but I didn’t receive it with the application:
![2023-01-19_17-02-23](https://user-images.githubusercontent.com/11975624/213463222-fe07911d-f854-4dcf-a6e3-675552538150.png)

And so I sent "Information" and received both there and there
![2023-01-19_17-05-16](https://user-images.githubusercontent.com/11975624/213463784-2103ec67-4848-4691-93b8-7db955c1f8ba.png)

I used your demo app only it didn't want to build and I changed the gradle version
classpath 'com.android.tools.build:gradle:7.1.2'
And I changed the version of agconnect
classpath 'com.huawei.agconnect:agcp:1.8.0.300'

**Comment by huseyinerenguler** [comment] 2023-01-20 07:11
Hello @mr-slonn 

In the _notification message_ notification, the reason why the notification does not appear on screen may be the system settings. Please make sure you allow **floating notifications (banners)** in phone notification settings. A notification appears in our demo application when the relevant setting is allowed.

![1-1](https://user-images.githubusercontent.com/26097484/213636672-237de131-6fd0-403f-9148-3ae82cf3ce6a.png)

Normally, when you send a _data message_ notification, it does not appear on screen. It is received by the application and you use it. The reason why it appeared on screen in our demo application is that we call _Push.localNotification_ method with data.

![2](https://user-images.githubusercontent.com/26097484/213635044-fd1744b0-cec9-46cb-8f30-1eb5d3c96bc7.png)

**Comment by mr-slonn** [comment] 2023-01-20 14:06
Thanks a lot!
Yes, you were right, the point is the permissions for "Banners", maybe you can tell me how to ask the user to agree to see this permission to display "Banners"?

**Comment by huseyinerenguler** [comment] 2023-01-31 13:20
Hi @mr-slonn 

It depends on the operating system (Android, iOS etc). You can use a third party package to get necessary **permissions** to show notifications.

**Closed** 2023-03-06 07:58 UTC
