### ISSUE TITLE
Crash after sign in with Huawei Id when returning to Flutter app

### ISSUE THREAD

**Issue by nank1ro** [HMS-Core/hms-flutter-plugin#8] opened 2020-08-24 09:08 UTC
After logging with Huawei ID with this code `await HmsAccount.signIn(authParamHelper);`, when is the time to return to the app to get the callback, I get the following error:
```
FATAL EXCEPTION: main
E/AndroidRuntime(29899): Process: com.nank1ro.learntocode.huawei, PID: 29899
E/AndroidRuntime(29899): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=8888, result=-1, data=Intent { (has extras) }} to activity {com.nank1ro.learntocode.huawei/com.nank1ro.learntocode.huawei.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(29899): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4846)
E/AndroidRuntime(29899): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
E/AndroidRuntime(29899): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(29899): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29899): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29899): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
E/AndroidRuntime(29899): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29899): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29899): 	at android.app.ActivityThread.main(ActivityThread.java:7403)
E/AndroidRuntime(29899): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29899): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29899): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/AndroidRuntime(29899): Caused by: java.lang.NullPointerException
E/AndroidRuntime(29899): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/AndroidRuntime(29899): 	at com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.java:234)
E/AndroidRuntime(29899): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(29899): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(29899): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(29899): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
E/AndroidRuntime(29899): 	at android.app.Activity.dispatchActivityResult(Activity.java:8119)
E/AndroidRuntime(29899): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
E/AndroidRuntime(29899): 	... 11 more
I/Process (29899): Sending signal. PID: 29899 SIG: 9
Lost connection to device.
```
Test Device: Xiaomi Mi A2
Android Version: 10

**Comment by aktug** [comment] 2020-08-24 11:41
Hello @nank1ro ;
Can you check MainActivity.java file and how did you import FlutterActivity in that file? 
and lastly, what is your flutter version?

**Comment by nank1ro** [comment] 2020-08-24 13:01
I have `MainActivity.kt`; the import is: `import io.flutter.embedding.android.FlutterActivity`
My flutter version is:
```
Flutter 1.20.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (11 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

**Comment by aktug** [comment] 2020-08-27 06:23
Hi @nank1ro 
We spotted what is the root cause for this issue, in the next version it will be fixed. 

Thanks a lot @nank1ro 🎉

**Closed** 2020-08-27 11:13 UTC
